Repository stackabletech/secret-operator, pull requests merged in 2025-03, with the labels that each got.

#567 docs: Fix the k8sSearch example
  docs/modules/secret-operator/pages/secretclass.adoc
Labels: area/documentation

#569 chore: Bump Rust dependencies pre-25.3.0
  CHANGELOG.md
  Cargo.lock
  Cargo.nix
  Cargo.toml
  crate-hashes.json
  rust/krb5-provision-keytab/src/active_directory.rs
  rust/krb5/src/kadm5.rs
  rust/krb5/src/lib.rs
  rust/operator-binary/src/backend/tls/mod.rs
  rust/operator-binary/src/main.rs
Labels: release/25.3.0

#566 fix: Set the issuer in generated TLS certificates to the subject of the issuing certificate
  CHANGELOG.md
  rust/operator-binary/src/backend/tls/mod.rs
Labels: customer-request, type/bug

#576 docs: Hint on kubelet dir special installation guides
  docs/modules/secret-operator/pages/troubleshooting.adoc
Labels: scheduled-for/25.3.0

#573 feat: Allow the specification of additional trust roots
  CHANGELOG.md
  deploy/helm/secret-operator/crds/crds.yaml
  deploy/helm/secret-operator/templates/roles.yaml
  docs/modules/secret-operator/pages/secretclass.adoc
  rust/crd-utils/src/lib.rs
  rust/operator-binary/src/backend/dynamic.rs
  rust/operator-binary/src/backend/tls/ca.rs
  rust/operator-binary/src/backend/tls/mod.rs
  rust/operator-binary/src/crd.rs
  tests/templates/kuttl/tls/02-rbac.yaml.j2
  tests/templates/kuttl/tls/03-create-trust-roots.yaml
  tests/templates/kuttl/tls/consumer.yaml
  tests/templates/kuttl/tls/secretclass.yaml.j2
Labels: scheduled-for/25.3.0

#578 docs: Document the SecretClass property additionalTrustRoots.configMap
  docs/modules/secret-operator/pages/secretclass.adoc
Labels: scheduled-for/25.3.0

#572 feat: Add format-specific annotations to override secret file names
  CHANGELOG.md
  docs/modules/secret-operator/pages/volume.adoc
  rust/operator-binary/src/backend/mod.rs
  rust/operator-binary/src/csi_server/node.rs
  rust/operator-binary/src/format/convert.rs
  rust/operator-binary/src/format/mod.rs
  rust/operator-binary/src/format/well_known.rs
  tests/templates/kuttl/tls/consumer.yaml.j2
  tests/test-definition.yaml
Labels: scheduled-for/25.7.0
